name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GitHub context
        run: |
          echo "Current repository: $GITHUB_REPOSITORY"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
